# Generated by Django 5.0.1 on 2024-01-17 16:05

import django.db.models.deletion
import myapps.order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodeUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('date_used', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(validators=[myapps.order.models.ValidationMixin.validate_payment])),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.staff')),
            ],
            bases=(models.Model, myapps.order.models.ValidationMixin),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('final_payment', models.FloatField(validators=[myapps.order.models.ValidationMixin.validate_payment])),
                ('pyment_status', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('C', 'Confirmed')], max_length=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('discount_code_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderr', to='order.discountcodeused')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, myapps.order.models.ValidationMixin),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(related_name='order', through='order.ProductOrder', to='product.product'),
        ),
    ]
