# Generated by Django 4.0 on 2024-02-13 21:02

from django.db import migrations, models
import django.db.models.deletion
import myapps.core.manager
import myapps.order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_remove_dicountpercent_product_id_and_more'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date_expiered', models.DateTimeField()),
                ('date_used', models.DateTimeField(default=None)),
                ('value', models.FloatField(validators=[myapps.order.models.ValidationMixin.validate_payment])),
                ('condition', models.FloatField(default=0, validators=[myapps.order.models.ValidationMixin.validate_payment])),
                ('code', models.CharField(max_length=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='member.customuser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='member.customuser')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, myapps.core.manager.DeleteMixin, myapps.order.models.ValidationMixin),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('final_payment', models.FloatField(validators=[myapps.order.models.ValidationMixin.validate_payment])),
                ('pyment_status', models.CharField(choices=[('Pending', 'Pending'), ('InHome', 'InHome'), ('Delivered', 'Delivered'), ('Confirmed', 'Confirmed')], max_length=9)),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='member.useraddress')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='member.customuser')),
                ('discount_code_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orderr', to='order.discountcode')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, myapps.core.manager.DeleteMixin),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            bases=(models.Model, myapps.core.manager.DeleteMixin),
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(related_name='order', through='order.ProductOrder', to='product.Product'),
        ),
    ]
