# Generated by Django 4.0 on 2024-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pyment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InHome', 'InHome'), ('Delivered', 'Delivered'), ('Confirmed', 'Confirmed')], max_length=9),
        ),
    ]
