# Generated by Django 5.0.1 on 2024-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcodeused',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
