# Generated by Django 4.0 on 2024-02-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='member.useraddress'),
        ),
    ]
