# Generated by Django 4.0 on 2024-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='date_used',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
