# Generated by Django 4.0 on 2024-02-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0003_alter_discountcode_date_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(on_delete=models.SET('address deleted'), related_name='address', to='member.useraddress'),
        ),
    ]
