# Generated by Django 4.0 on 2024-02-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        ('order', '0004_alter_order_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='address', to='member.useraddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_code_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(1), related_name='orderr', to='order.discountcode'),
        ),
    ]
