# Generated by Django 4.0 on 2024-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicountpercent',
            name='detail_id',
            field=models.ForeignKey(on_delete=models.SET('the product delete'), to='product.detail'),
        ),
    ]
