# Generated by Django 4.0 on 2024-02-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicountpercent',
            name='product_id',
        ),
        migrations.AddField(
            model_name='dicountpercent',
            name='detail_id',
            field=models.ManyToManyField(to='product.Detail'),
        ),
    ]
