# Generated by Django 5.0.1 on 2024-01-30 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_detail_product_detail_detaill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productt', to='product.product'),
        ),
    ]
